# Generated by Django 3.2.6 on 2021-08-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='words',
            table='search',
        ),
    ]
