# Generated by Django 3.2.6 on 2021-08-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_words_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wrong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_one', models.CharField(max_length=20)),
                ('words_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.words')),
            ],
        ),
    ]
