# Generated by Django 3.2.6 on 2021-08-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_wrong'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='words',
            table='words',
        ),
        migrations.AlterModelTable(
            name='wrong',
            table='wrong',
        ),
    ]
