# Generated by Django 3.1.7 on 2021-08-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20210818_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
